### ISSUE TITLE
Make runtest on Github Action Cron featrue.

### ISSUE THREAD

**Issue by paranlee** [namhyung/uftrace#1738]
If we utilizing `make runtest` on github actions cron feature would be nice!
It seems like we can verify the behavior on the x64 architecture and then extend it to other supported architectures.

### [Github Actions Cron](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)
A single workflow can be triggered by multiple schedule events. You can access the schedule event that triggered the workflow through the github.event.schedule context. This example triggers the workflow to run at 5:30 UTC every Monday-Thursday, but skips the Not on Monday or Wednesday step on Monday and Wednesday.
```yml
on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
Cron syntax has five fields separated by a space, and each field represents a unit of time.
```
```
┌───────────── minute (0 - 59)
│ ┌───────────── hour (0 - 23)
│ │ ┌───────────── day of the month (1 - 31)
│ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
│ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
│ │ │ │ │
│ │ │ │ │
│ │ │ │ │
* * * * *
```
