### ISSUE TITLE
Nightly-test for Multi-platform architectures support

### ISSUE THREAD

**Issue by paranlee** [namhyung/uftrace#1739]
[nightly-test.yml](https://github.com/namhyung/uftrace/blob/master/.github/workflows/nightly-test.yml) have ubuntu-2x tests.
We can find [test result](https://github.com/namhyung/uftrace/actions/runs/5344734372/jobs/9689479941#step:7:185).
It seems like we can extend it to other architectures support.
- https://docs.docker.com/build/building/multi-platform/
```
$ docker run --privileged --rm tonistiigi/binfmt --install all
$ docker run -it --rm --platform linux/arm64 arm64v8/ubuntu sh
```
This Tool have currently support emulations.
- https://jkfran.com/running-ubuntu-arm-with-docker/
- https://github.com/tonistiigi/binfmt
```
docker run --rm arm64v8/alpine uname -a
docker run --rm arm32v7/alpine uname -a
docker run --rm ppc64le/alpine uname -a
docker run --rm s390x/alpine uname -a
docker run --rm tonistiigi/debian:riscv uname -a
```
![image](https://github.com/namhyung/uftrace/assets/43713967/faba6f00-cdd5-4a7b-8523-4e8f18f4922f)

**Comment by namhyung** [comment]
As I said in another issue, we cannot extend the test matrix due to price.

**Comment by paranlee** [comment]
@namhyung In Xen project, They are using [Gitlab CI](https://gitlab.com/xen-project/xen/-/blob/staging/automation/gitlab-ci/test.yaml) by mirroring the repository on [each arch](https://gitlab.com/xen-project/xen/-/tree/staging/automation/scripts). What do you think of this? They are also using [Github workflow on coverity](https://github.com/xen-project/xen/blob/master/.github/workflows/coverity.yml).

**Comment by namhyung** [comment]
I'm not sure but Gitlab also won't offer infinite resources.  We need to check their price policies.  Xen is a big project and IIUC it gets commercial supports.

But I'm open to improving CI infra in any direction.  Please go ahead and suggest something useful! :)

**Comment by paranlee** [comment]
I find another examples on Github Actions.
- https://support.circleci.com/hc/en-us/articles/17034320054811-How-to-run-arm64-docker-images
```yml
version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: arm.medium
    steps:
      - checkout
      - run: 
          name: Start arm docker container
          command: |
            docker run -idt --platform linux/arm64/v8 --name ruby ruby:3.2.2-slim
            docker exec -it ruby bash -c "uname -m"

workflows:
  arm-workflow:
    jobs:
      - test
```
