### ISSUE TITLE
Nightly-test with privileged

### ISSUE THREAD

**Issue by paranlee** [namhyung/uftrace#1741]
Nightly-test test have been executed with user level. 
Wouldn't it be possible to perform tests with [root privileges](https://github.com/namhyung/uftrace/blob/master/.github/workflows/nightly-test.yml#L29) that would be skipped by user?
```yml
      - name: "setup run-time env"
        run: |
          sudo sh -c "echo 1 > /proc/sys/kernel/perf_event_paranoid"
          sudo sh -c "echo 0 > /proc/sys/kernel/kptr_restrict"
          sudo sh -c "chmod +x /sys/kernel/tracing"

      - name: "run tests"
        run: make test -j1 TESTARG='--color on' RUNTESTARG='--quiet'
```
