### ISSUE TITLE
test: Run test suite on multiple environments

### ISSUE THREAD

**Issue by clementguidi** [namhyung/uftrace#1908]
Hi,

As we recently realized (#1903), the current test runs are not able to catch breaking changes for some environments. This is obviously expected as you cannot test on every environment (kernel/arch/compiler) possible.

I can see the nightly tests in GH Actions are restricted to one image. What other envs are you able to test on?

Do you think we could test uftrace in more environments? Especially on a broader spectrum of compilers and kernels.

I understand this represents a big effort. I was curious to know your position on this?

**Comment by namhyung** [comment]
Hi, actually I didn't research all the possibilities that provide free CI infra and just use GH for now.  I don't think I can increase the testing matrix in the Github free tier.  I'm open to suggestions. :)

**Comment by junyeong0619** [comment]
How about using matrix in GITHUB ACTION? 
like this : 
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-9, gcc-11, clang-12, clang-14]
        os_container: ['ubuntu:20.04', 'ubuntu:22.04', 'rockylinux:9']
    
    container: ${{ matrix.os_container }}
```
Or using container from docker in GITHUB ACTION?
like this : 
```yaml
jobs:
  test-legacy-environments:
    runs-on: ubuntu-latest
    
    container: oraclelinux:7  # It works with images in Docker
```
